version: '3.3'
services:
  ms-cars-server:
    depends_on:
      - db
    container_name: ms-cars-server
    build:
      context: .
      dockerfile: Dockerfile.cars
    image: ms-cars-server:latest
    expose:
      - 8080
    ports:
      - 8070:8080
    networks:
      - spring-cloud-network
    links:
      - db:db
    logging:
      driver: json-file
    environment:
      spring.profiles.active: dev

  ms-users-server:
    depends_on:
      - db
    container_name: ms-users-server
    build:
      context: .
      dockerfile: Dockerfile.users
    image: ms-users-server:latest
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - spring-cloud-network
    links:
      - db:db
    logging:
      driver: json-file
    environment:
      spring.profiles.active: dev

  db:
    image:
      mysql:latest
    container_name:
      mysql-container1
    restart:
      always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: devdb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '2012:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - /home/thor/crv_mysql:/var/lib/mysql
    networks:
      - spring-cloud-network

  nginx:
    image: nginx:latest
    container_name: ms_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:8080
    networks:
      - spring-cloud-network
    depends_on:
      - ms-cars-server
      - ms-users-server

networks:
  spring-cloud-network:
    driver: bridge