FROM java:8
LABEL maintainer=“great_dev@mail.com”
VOLUME /tmp2
EXPOSE 8080
ADD /spring-boot-ms-cars/target/spring-boot-ms-cars-0.0.1-SNAPSHOT.jar spring-boot-ms-cars-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","spring-boot-ms-cars-0.0.1-SNAPSHOT.jar"]